### PR TITLE
Enable MU

### PR DESCRIPTION
**Pull request by gossi**
This PR is about making ember-cli-tailwind available for MU. There are four things that needs to be done here:

- [x] Read input from `src/tailwind`
- [x] Put the compiled tailwind css into the correct location (`BuildTailwindPlugin` and the correct `destFile` location)
- [ ] Adjust the instance-initializer to work in a MU setting (e.g. `import Router from '../router';` won't resolve in MU)
- [ ] Adjust blueprint to put files in `src/` rather than `app/`

I already have the first one achieved (which was the easy one). However, now I'm stuck, making the generated files being picked up by the host (with `BuildTailwindPlugin`). I've tried all kinds of combinations of what the  `destFile` should be, without success. I need help for this one.

Ping me in slack.

### CODE REVIEW

**Comment by gossi** [comment]
I adopted tests from #43 (great job guys) and finally was able to inject tailwind into the right tree of the host project which will load it (`treeForSrc()`). So you can use a MU app with this branch now 👍

**Comment by fpauser** [comment]
MU?

**Comment by EndangeredMassa** [comment]
Can we get this updated? Is this something I could help with?

**Comment by gossi** [comment]
I most probably won't continue doing this. I only did this to test out utility-css which I found out doesn't match my style. Though, I did some initial work, so feel free to jump on it and bring it over the finish line :)

**Comment by samselikoff** [comment]
@gossi really appreciate your help here! Curious what you're using now?

@EndangeredMassa I have not touched MU yet in any of my apps or addons, because it feels churn-y. Are you all using it? I am unsure of its future right now so hesitant to add support to it...

**Comment by EndangeredMassa** [comment]
@samselikoff I was trying out the ember octane blueprint and wanted to use tailwind as well. I have no special insight into the progress/plans of MU. I think I'll use tailwind outside of this module for now and come back to this after Octane is officially released.

**Comment by samselikoff** [comment]
Kind of want to close this until MU stabilizes. Sound ok?

**Comment by rwwagner90** [comment]
@samselikoff since MU was punted on, I think closing until it is released would be smart.

**Pull request closed without merging**
