### PR TITLE
Support for module unification folder

### PR DESCRIPTION
**Pull request by hakubo**

### CODE REVIEW

**Comment by samselikoff** [comment]
Thank you!

Could we get a new test added [here](https://github.com/embermap/ember-cli-tailwind/blob/master/node-tests/build-target-test.js)?

**Comment by hakubo** [comment]
will do next week,
also - not sure if that works :)
so give me couple of more days to finish that

**Comment by hakubo** [comment]
@samselikoff turns out much more is needed to support MU layout
I have gone to the point that tests run
everything should be fine

but actual thing that we're trying to do here is not working
could you have a look and point me in the right direction?

since this needs master of ember-cli to run now - probably you won't be merging that soon
but I'd like to test drive it in my side project so I'd be glad to get some help with it

**Comment by willviles** [comment]
It'd be great to get this addon working with module unification. I believe these are the issues:

`treeForStyles` isn't used by module unification apps. Instead, everything is merged together via `app.trees.src`. See https://github.com/ember-cli/ember-cli/issues/7862. 

However, at the moment there's a blocking issue with merging trees into `app.trees.src`, caused by a validation error with Ember CLI ESLint: https://github.com/ember-cli/ember-cli-eslint/issues/56.

**Comment by samselikoff** [comment]
@willviles are y'all using MU today? It was my understanding that much could change about MU before it gets shipped and I'm a little hesitant to add a bunch of code to ec-tailwind to support an unstable feature...

Happy to do it if it makes sense though

**Comment by willviles** [comment]
I'm not migrating our production apps to MU yet as compatibility with addons is clearly sketchy. However, I'm testing out a small static marketing site with module unification and reporting problems as I go.

I'll dig a little deeper and find out whether there's a stable path for addons to support MU and what's blocking that from happening 👍

**Comment by samselikoff** [comment]
Awesome, thank you very much & looking forward to what you find. (Latest thing I saw that made me hesitant was [this comment](https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill/issues/27#issuecomment-404554170), perhaps Robert + crew have more information.)

**Comment by willviles** [comment]
Sure - I think that particular comment was relating to a separate RFC titled [Module Unification Namespaces](https://github.com/mixonic/rfcs/blob/5be49c7c0367dbf72464a6402122cf89b927ac00/text/0000-module-unification-namespaces.md) and specifically the use of the new `{{use}}` helper, rather than the accepted and well rationalized [Module Unification RFC](https://github.com/mixonic/rfcs/blob/5be49c7c0367dbf72464a6402122cf89b927ac00/text/0143-module-unification.md).

Albeit there's still a fair bit left to be implemented in the [quest issue](https://github.com/emberjs/ember.js/issues/16373) for MU!

**Comment by samselikoff** [comment]
I see – then yes we should support it. Seems like it's come up a few times

**Comment by hakubo** [comment]
Thanks @gossi for pushing this foraward

**Pull request closed without merging**
